# Generated by Django 4.0.6 on 2022-07-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample_no',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sample_No', models.CharField(max_length=32)),
                ('Model_Code', models.CharField(max_length=32)),
                ('Sub_Category', models.CharField(max_length=64)),
                ('Curr_Location', models.CharField(max_length=64)),
                ('Curr_Assignee', models.CharField(max_length=32)),
                ('STPI', models.CharField(max_length=32)),
            ],
        ),
    ]
